---
title: "Pset3b"
author: "Emily Dunn"
format: pdf
editor: visual
execute: 
  warning: FALSE
---

```{r, setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy.opts = list(
  width.cutoff = 50), tidy = T, cache = F, warning = F,
  message = F)

library(tidyr);
library(tidyverse);
library(dplyr);
library(ggplot2);
library(tinytex);
library(kableExtra);
library(ggthemes);
library(palmerpenguins)

setwd("/Users/oneone/Documents/MIT Fall '25/17.800 Quant 1/Math Camp/Problem Sets/")

```

```{r}
# 1

(A <- matrix(c(1, 4, 5, 6, 9, 12, 4, 1, 9), nrow = 3,
                ncol = 3, byrow = TRUE) )
(B <- matrix(c(1, 2, 8, 9, 3, 8, 2, 2, 0),
            nrow = 3, byrow = TRUE) )
(C <- matrix(c(8, 9, 10, 4, 7, 9),
             nrow = 2, byrow = TRUE) )

# 2
(AplusB <- A + B)
(CplusB <- NA) # Matrix C and B are not comformable 
(AxB <- A %*% B)
(Ainv <- solve(A) )
(AtxAinv <- solve(t(A) %*% A) )

# 3
(coef.matrix <- matrix(c(3, 5, 2, 1, 5, 5, 3, 3, 9, -1, 0, 2,
                        2, 2, -5, -4), nrow = 4, byrow = TRUE
                       ) )
(Y <- matrix(c(1, -1, 3, 4), nrow = 4 ) )

(solution <- solve(coef.matrix) %*% Y ) 
# final answers a, b, c, d
```
